# Generated by Django 4.2.7 on 2023-12-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Home Background Image',
                'verbose_name_plural': 'Home Background Images',
            },
        ),
    ]
