# Generated by Django 4.2.7 on 2023-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homebg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebg',
            name='image',
        ),
        migrations.AddField(
            model_name='homebg',
            name='image1',
            field=models.ImageField(null=True, upload_to='media', verbose_name='First Background Images'),
        ),
        migrations.AddField(
            model_name='homebg',
            name='image2',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Second Background Images'),
        ),
        migrations.AddField(
            model_name='homebg',
            name='image3',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Third Background Images'),
        ),
        migrations.AddField(
            model_name='homebg',
            name='image4',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Forth Background Images'),
        ),
    ]
