# Generated by Django 4.2.7 on 2023-12-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_homebg_image_homebg_image1_homebg_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Services Text',
                'verbose_name_plural': 'Services Texts',
            },
        ),
    ]
