# Generated by Django 4.2.7 on 2023-12-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ourgallery_ourservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourservice',
            options={'verbose_name': 'Our Services ', 'verbose_name_plural': 'Our Services'},
        ),
    ]
