# Generated by Django 4.2.7 on 2023-12-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ourservice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservice',
            name='text',
        ),
        migrations.AddField(
            model_name='ourservice',
            name='text1',
            field=models.TextField(max_length=255, null=True, verbose_name='First Text'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='text2',
            field=models.TextField(max_length=255, null=True, verbose_name='Second Text'),
        ),
    ]
