# Generated by Django 4.2.7 on 2023-12-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_ourservice_text_ourservice_text1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourgallery',
            options={'verbose_name': 'Our Gallery', 'verbose_name_plural': 'Our Galleries'},
        ),
        migrations.AddField(
            model_name='ourgallery',
            name='img_large',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Large Image'),
        ),
        migrations.AddField(
            model_name='ourgallery',
            name='img_small',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Small Image'),
        ),
        migrations.AddField(
            model_name='ourgallery',
            name='subtitle',
            field=models.CharField(max_length=50, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='ourgallery',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
    ]
