# Generated by Django 4.2.7 on 2023-12-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_ourgallery_options_ourgallery_img_large_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(max_length=255, verbose_name='First Text')),
                ('text2', models.TextField(max_length=255, verbose_name='Second Text')),
                ('text3', models.TextField(max_length=255, verbose_name='Third Text')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Uses',
            },
        ),
    ]
