# Generated by Django 4.2.8 on 2023-12-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
