# Generated by Django 4.2.8 on 2023-12-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contactus_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourgallery',
            old_name='img_small',
            new_name='img',
        ),
    ]
