# Generated by Django 4.2.8 on 2023-12-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_img_small_ourgallery_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourgallery',
            name='img_large',
        ),
        migrations.AddField(
            model_name='ourgallery',
            name='img_small',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Small Image'),
        ),
        migrations.AlterField(
            model_name='ourgallery',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Large Image'),
        ),
    ]
