# Generated by Django 4.2.8 on 2023-12-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_ourgallery_img_small_ourgallery_img_large_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Contact Text',
                'verbose_name_plural': 'Contact Texts',
            },
        ),
    ]
