# Generated by Django 4.2.8 on 2023-12-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contacttxt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon')),
                ('text', models.TextField(max_length=255, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
    ]
